name: hinode-2023-loops-poster
channels:
- conda-forge
dependencies:
- python
- pip
- pip:
  - snakemake
  - sunpy[all]
  - ndcube
  - aiapy
  - eispac
  - xrtpy
  - sunkit-image
  - fiasco
  - demcmc
  - boto3
  - s3fs
  - distributed
  - ipykernel
  - git+https://github.com/wtbarnes/synthesizAR.git
